### PR TITLE
Fix crash in Whisper Transcription when used from Macro

### PR DESCRIPTION
**Pull request by RyanMetcalfeInt8**
Resolves https://github.com/intel/openvino-plugins-ai-audacity/issues/160

### CODE REVIEW

**Comment by RyanMetcalfeInt8** [comment]
Fix for whisper is here, but need to test use of macros for music gen, noise suppression, and music separation.

**Comment by RyanMetcalfeInt8** [comment]
ok, tagging this ready for review. 

I ideally wanted to test music gen with macros as well (as I do see value in creating a macro that uses music gen to generate N snippets), and fix any issues that pop up there, but testing is blocked by this issue:  https://github.com/audacity/audacity/issues/6410

So, I'll have to tackle that later on.

**Review by arisha07 — APPROVED** [review]
LGTM

**Comment by joedale100** [comment]
Thank you, Ryan. Will you be releasing a patch for this?

**Comment by RyanMetcalfeInt8** [comment]
Hi @joedale100,

Yes, I hope to release something by end of this week. Cheers!

**Comment by joedale100** [comment]
Thanks for letting me know, Ryan :-)

**Pull request merged**
